window.CODE_PROJECTS = [
  {
    id: 'coffeemaker',
    name: 'CoffeeMaker',
    subtitle: 'Full-Stack Beverage Ordering System (Spring Boot + React)',
    files: [
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/CoffeeMakerApplication.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/controllers/IngredientController.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/controllers/InventoryController.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/controllers/MakeRecipeController.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/controllers/RecipeController.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/dto/IngredientDto.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/dto/InventoryDto.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/dto/RecipeDto.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/entity/Ingredient.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/entity/Inventory.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/entity/Recipe.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/exception/ResourceNotFoundException.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/mapper/IngredientMapper.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/mapper/InventoryMapper.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/mapper/RecipeMapper.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/repositories/IngredientRepository.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/repositories/InventoryRepository.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/repositories/RecipeRepository.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/services/IngredientService.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/services/InventoryService.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/services/MakeRecipeService.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/services/RecipeService.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/services/impl/IngredientServiceImpl.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/services/impl/InventoryServiceImpl.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/services/impl/MakeRecipeServiceImpl.java',
      'backend/src/main/java/edu/ncsu/csc326/coffee_maker/services/impl/RecipeServiceImpl.java',
      'backend/src/main/resources/application.properties',
      'backend/src/test/java/edu/ncsu/csc326/coffee_maker/TestUtils.java',
      'backend/src/test/java/edu/ncsu/csc326/coffee_maker/controllers/InventoryControllerTest.java',
      'backend/src/test/java/edu/ncsu/csc326/coffee_maker/controllers/InventoryControllerWebMvcTest.java',
      'backend/src/test/java/edu/ncsu/csc326/coffee_maker/controllers/RecipeControllerTest.java',
      'backend/src/test/java/edu/ncsu/csc326/coffee_maker/controllers/RecipeControllerWebMvcTest.java',
      'backend/src/test/java/edu/ncsu/csc326/coffee_maker/entity/RecipeTest.java',
      'backend/src/test/java/edu/ncsu/csc326/coffee_maker/repositories/InventoryRepositoryTest.java',
      'backend/src/test/java/edu/ncsu/csc326/coffee_maker/repositories/RecipeRepositoryTest.java',
      'backend/src/test/java/edu/ncsu/csc326/coffee_maker/services/InventoryServiceTest.java',
      'backend/src/test/java/edu/ncsu/csc326/coffee_maker/services/RecipeServiceTest.java',
      'backend/src/test/resources/application.properties',
      'backend/pom.xml',
      'backend/.env.template',
      'backend/config/checkstyle/csc_checkstyle.xml',
      'frontend/src/main.jsx',
      'frontend/src/App.jsx',
      'frontend/src/App.css',
      'frontend/src/index.css',
      'frontend/src/components/AddIngredientComponent.jsx',
      'frontend/src/components/EditRecipeWSComponent.jsx',
      'frontend/src/components/FooterComponent.jsx',
      'frontend/src/components/HeaderComponent.jsx',
      'frontend/src/components/InventoryComponent.jsx',
      'frontend/src/components/ListRecipesComponent.jsx',
      'frontend/src/components/MakeRecipeComponent.jsx',
      'frontend/src/components/RecipeComponent.jsx',
      'frontend/src/services/ApiConfig.js',
      'frontend/src/services/InventoryService.js',
      'frontend/src/services/MakeRecipeService.js',
      'frontend/src/services/RecipesService.js',
      'frontend/public/coffee.svg',
      'frontend/index.html',
      'frontend/package.json',
      'frontend/vite.config.js',
      'frontend/eslint.config.js',
      'frontend/README.md',
    ],
  },
  {
    id: 'wolfdash',
    name: 'WolfDash',
    subtitle: 'Ride-Share Management System (RideShareManager)',
    files: [
      'src/edu/ncsu/csc316/ride/manager/RideShareManager.java',
      'src/edu/ncsu/csc316/ride/manager/ReportManager.java',
      'src/edu/ncsu/csc316/ride/ui/RideShareManagerUI.java',
      'test/edu/ncsu/csc316/ride/manager/RideShareManagerTest.java',
      'test/edu/ncsu/csc316/ride/manager/ReportManagerTest.java',
      'input/drivers.csv',
      'input/drivers_empty.csv',
      'input/events.csv',
      'input/events_empty.csv',
      'input/events_no_violations.csv',
      'input/events_reverse.csv',
    ],
  },
  {
    id: 'wolfregrade',
    name: 'WolfRegrade',
    subtitle: 'Regrade Request Management System',
    files: [
      'model/course/Course.java',
      'model/course/Assignment.java',
      'model/regrade/RegradeRequest.java',
      'model/regrade/ClarifyRequest.java',
      'model/regrade/ExemptionRequest.java',
      'model/regrade/ResubmitRequest.java',
      'model/regrade/ReviewRequest.java',
      'model/io/RegradeReader.java',
      'model/io/RegradeWriter.java',
      'model/util/SortedList.java',
      'model/util/BackLog.java',
      'model/util/CompletedRegradesStack.java',
      'model/util/ISortedList.java',
      'model/util/IBackLog.java',
      'model/util/IStack.java',
      'model/util/Iterable.java',
      'model/util/Iterator.java',
      'view/ui/WolfRegradeGUI.java',
    ],
  },
];
